[package]
name = "stable-buffer"
version = "1.0.0"
description = "Buffers implemented in stable memory regions"
repository = "\u0016https://github.com/bittoko/stable-buffer"
keywords = [ "buffer", "array", "stable", "memory", "region" ]
license = "MIT"

[dependencies]
base = "0.10.4"
test = "1.2.0"